# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------
QT += core opengl gui multimedia widgets openglextensions
TEMPLATE = app
TARGET = XPlay2
DESTDIR = ../../bin/win32
CONFIG += debug console
LIBS += -L"./../../lib/win32"
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
include(XPlay2.pri)
